"""
Dhan (DhanHQ API v2) authentication.

Unlike Kite Connect, Dhan has no request_token/OAuth handshake for a single
personal account -- the very first token still has to be generated by hand
at https://web.dhan.co (Profile -> "Access DhanHQ Trading APIs") and pasted
in via `python -m dhan.auth <ACCESS_TOKEN>". From then on, though, tokens
renew themselves automatically -- see renew_access_token() below and
dhan/cron_renew_token.py, scheduled daily at 8:00am IST.

Usage from any script:
    from dhan.auth import get_session

    session, client_id = get_session()
    resp = session.get(f"{BASE_URL}/fundlimit")

Run directly to save a freshly generated token (only needed once, or if
automated renewal has been failing and the saved token has fully expired):
    python -m dhan.auth <ACCESS_TOKEN>

Token lifecycle (per DhanHQ docs, confirmed live 2026-08-25):
    Access tokens are valid 24h from generation. GET /v2/RenewToken (headers
    "access-token" + "dhanClientId", same as every other call) returns a
    fresh token good for another 24h -- see renew_access_token(). Two
    gotchas confirmed by hand before wiring this in:
      - It MUST be a GET request. POST and PUT both return a DH-905
        "Missing required fields" error, which reads like a client mistake
        but is really just the wrong HTTP verb.
      - Renewing invalidates the PREVIOUS token immediately -- there is no
        overlap window where both old and new tokens work. Anything holding
        the old token in memory at the moment of renewal starts failing
        right after. This is why dhan/cron_renew_token.py runs at 8:00am AND
        8:00pm daily -- both comfortably inside the dead zone after the
        previous day's live_monitor.py was killed (3:40pm) and before the
        next one starts (9:10am), so nothing is ever actively using the
        token when it gets swapped out. Twice a day, not once: a fixed
        once-daily cron would fire almost exactly 24h after the last
        renewal, leaving only a second or two of buffer before the old
        token's real expiry -- a single slow tick or API hiccup could miss
        the window entirely. Renewing every 12h instead keeps a comfortable
        multi-hour buffer at all times.
"""

import json
import os
import sys
from pathlib import Path
from datetime import datetime, timedelta
from zoneinfo import ZoneInfo

import requests
from dotenv import load_dotenv

_ENV_FILE = Path(__file__).resolve().parent.parent / "pipeline" / ".env"
load_dotenv(_ENV_FILE)

_BASE_URL   = "https://api.dhan.co/v2"
_TOKEN_FILE = os.path.join(os.path.dirname(__file__), ".token.json")
_IST        = ZoneInfo("Asia/Kolkata")

_CLIENT_ID = (os.getenv("DHAN_CLIENT_ID") or "").strip()


# ── Token file helpers ─────────────────────────────────────────────────────────

def _save_token(access_token: str) -> dict:
    issued  = datetime.now(_IST)
    expires = issued + timedelta(hours=24)
    payload = {
        "access_token": access_token,
        "issued_at":    issued.isoformat(),
        "expires_at":   expires.isoformat(),
    }
    with open(_TOKEN_FILE, "w") as f:
        json.dump(payload, f, indent=2)
    print(f"[dhan] Token saved → {_TOKEN_FILE}  (expires {expires.strftime('%Y-%m-%d %H:%M %Z')})")
    return payload


def _load_valid_token() -> str | None:
    """Returns access_token if the saved token is still valid, else None."""
    if not os.path.exists(_TOKEN_FILE):
        print("[dhan] No saved token found — run `python -m dhan.auth <ACCESS_TOKEN>`.")
        return None
    try:
        with open(_TOKEN_FILE) as f:
            data = json.load(f)
        expires_at = datetime.fromisoformat(data["expires_at"])
    except Exception as exc:
        print(f"[dhan] Could not read token file ({exc}) — new token required.")
        return None

    if datetime.now(_IST) >= expires_at:
        print(f"[dhan] Token expired at {expires_at.strftime('%Y-%m-%d %H:%M %Z')} — "
              "generate a new one at web.dhan.co and run `python -m dhan.auth <ACCESS_TOKEN>`.")
        return None

    issued = data.get("issued_at", "")[:16]
    print(f"[dhan] Reusing valid token (issued {issued}, expires {expires_at.strftime('%H:%M %Z')})")
    return data["access_token"]


# ── Public API ─────────────────────────────────────────────────────────────────

class DhanAuthError(RuntimeError):
    """Raised when there's no valid token and no way to get one automatically."""


def renew_access_token() -> tuple[bool, str]:
    """
    Renews today's saved token via GET /v2/RenewToken, verifies the new
    token actually works via a real /fundlimit call, and ONLY THEN
    overwrites dhan/.token.json (via _save_token). On any failure -- the
    renew call itself, or the verification call -- the existing saved token
    is left completely untouched, so a failed renewal attempt never leaves
    the system with no working token at all (see module docstring for why
    renewal must run when nothing else is using the token).

    One sharp edge worth knowing: if the renew call itself SUCCEEDS but the
    verification call then fails (e.g. a network blip right after), the
    previous token is already dead on Dhan's side by that point -- renewal
    invalidates it immediately regardless of what this function does next.
    "Leave the file untouched" avoids saving an unverified token, but it
    does NOT guarantee the token left in the file still works. That specific
    case is rare (verification hits the same API moments after a successful
    renew) but is not fully self-healing -- a manual `python -m dhan.auth
    <TOKEN>` may still be needed if it happens. Flagged here rather than
    silently assumed away.

    Returns (success, message) rather than raising, so a cron wrapper can
    decide what to do (log, alert, exit code) without needing to catch
    exceptions for an expected, recoverable failure mode.
    """
    if not _CLIENT_ID:
        return False, "DHAN_CLIENT_ID not set in pipeline/.env"

    if not os.path.exists(_TOKEN_FILE):
        return False, ("No existing token file to renew from -- run "
                       "`python -m dhan.auth <ACCESS_TOKEN>` first.")

    try:
        with open(_TOKEN_FILE) as f:
            current_token = json.load(f)["access_token"]
    except Exception as exc:
        return False, f"Could not read current token file: {exc}"

    try:
        resp = requests.get(
            f"{_BASE_URL}/RenewToken",
            headers={"access-token": current_token, "dhanClientId": _CLIENT_ID},
            timeout=15,
        )
    except Exception as exc:
        return False, f"RenewToken request failed: {exc}"

    if resp.status_code != 200:
        return False, f"RenewToken returned HTTP {resp.status_code}: {resp.text[:300]}"

    try:
        new_token = resp.json()["token"]
    except Exception as exc:
        return False, f"RenewToken response missing 'token' field ({exc}): {resp.text[:300]}"

    # Verify the new token for real before trusting it -- don't just believe
    # the RenewToken response body (the old token is already dead by this
    # point regardless, per the docstring above).
    try:
        verify_resp = requests.get(
            f"{_BASE_URL}/fundlimit",
            headers={"access-token": new_token, "dhanClientId": _CLIENT_ID},
            timeout=15,
        )
    except Exception as exc:
        return False, (f"New token verification request failed (previous token is "
                       f"already invalid -- see docstring): {exc}")

    if verify_resp.status_code != 200:
        return False, (f"New token failed /fundlimit verification "
                       f"(HTTP {verify_resp.status_code}): {verify_resp.text[:300]}")

    saved = _save_token(new_token)
    return True, f"Token renewed successfully, expires {saved['expires_at']}"


def get_session() -> tuple[requests.Session, str]:
    """
    Returns (session, client_id).

    - Reuses today's saved token if not expired.
    - Raises DhanAuthError if no valid token exists (there's no browser flow
      to fall back to -- unlike Kite, Dhan's direct-token model requires a
      human to paste a freshly generated token; see module docstring).

    Usage:
        session, client_id = get_session()
        resp = session.get(f"{BASE_URL}/fundlimit")
    """
    if not _CLIENT_ID:
        raise EnvironmentError("[dhan] DHAN_CLIENT_ID is not set in pipeline/.env")

    access_token = _load_valid_token()
    if access_token is None:
        raise DhanAuthError(
            "[dhan] No valid Dhan token. Generate one at web.dhan.co "
            "(Profile → Access DhanHQ Trading APIs) and run:\n"
            "  python -m dhan.auth <ACCESS_TOKEN>"
        )

    session = requests.Session()
    session.headers.update({
        "access-token": access_token,
        "dhanClientId": _CLIENT_ID,
        # Data API endpoints (marketfeed/ltp, marketfeed/quote, optionchain) check a
        # separate "client-id" header, not "dhanClientId" -- without it they 401 with
        # {"810":"ClientId is invalid"} even on a fresh token. Confirmed 2026-08-17
        # against Dhan's own example curl requests, which show both header names used
        # depending on endpoint (Trading APIs only need dhanClientId/no header at all;
        # Data APIs need client-id).
        "client-id":    _CLIENT_ID,
        "Content-Type": "application/json",
        "Accept":       "application/json",
    })
    return session, _CLIENT_ID


BASE_URL = _BASE_URL


# ── CLI entry point ────────────────────────────────────────────────────────────

if __name__ == "__main__":
    print(f"[dhan] BASE_URL = {_BASE_URL}")
    print()

    if len(sys.argv) < 2:
        print("Usage: python -m dhan.auth <ACCESS_TOKEN>", file=sys.stderr)
        print("Generate a token at web.dhan.co → Profile → Access DhanHQ Trading APIs", file=sys.stderr)
        sys.exit(1)

    if not _CLIENT_ID:
        print("Error: DHAN_CLIENT_ID is not set in pipeline/.env", file=sys.stderr)
        sys.exit(1)

    access_token = sys.argv[1].strip()
    _save_token(access_token)

    session = requests.Session()
    session.headers.update({
        "access-token": access_token,
        "dhanClientId": _CLIENT_ID,
        "client-id":    _CLIENT_ID,
        "Content-Type": "application/json",
        "Accept":       "application/json",
    })

    print("\n[dhan] Verifying via fund limit endpoint...")
    resp = session.get(f"{_BASE_URL}/fundlimit", timeout=10)

    if resp.ok:
        data = resp.json()
        print("[dhan] Login verified.")
        print(f"  Client ID          : {data.get('dhanClientId', _CLIENT_ID)}")
        print(f"  Available balance   : ₹{data.get('availabelBalance', 'n/a')}")
        print(f"  SOD limit           : ₹{data.get('sodLimit', 'n/a')}")
        print(f"  Utilized amount     : ₹{data.get('utilizedAmount', 'n/a')}")
    else:
        print(f"[dhan] Fund limit check failed: HTTP {resp.status_code}", file=sys.stderr)
        print(resp.text, file=sys.stderr)
        print(
            "\n[dhan] If this is a 401/403, the header name may need adjusting "
            "(dhanClientId vs client-id) -- check the response body above.",
            file=sys.stderr,
        )
        sys.exit(1)
